In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv("../data/raw/amazon.csv")

df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,269","High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|Durability : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|High Security Level : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|WARRANTY: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_1?qid=1672909124&s=electronics&sr=1-1
1,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be it an android smartphone (Mi, Samsung, Oppo, Vivo, Realme, OnePlus, etc), tablet, laptop (Macbook, Chromebook, etc)|Supports Quick Charging (2.0/3.0)|Unbreakable – Made of special braided outer with rugged interior bindings, it is ultra-durable cable that won’t be affected by daily rough usage|Ideal Length – It has ideal length of 1.5 meters which is neither too short like your typical 1meter cable or too long like a 2meters cable|Supports maximum 3A fast charging and 480 Mbps data transfer speed|6 months manufacturer warranty from the date of purchase","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBXNGXZJT525AQ,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,AEPSWFPNECKO34PUC7I56ITGXR6Q,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,AH4QT33M55677I7ISQOAKEQWACYQ","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Placeholder,BharanI,sonia,Niam","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU","A Good Braided Cable for Your Type C Device,Good quality product from ambrane,Super cable,As,Good quality,Good product,its good,Good quality for the price but one issue with my unit","I ordered this cable to connect my phone to Android Auto of car. The cable is really strong and the connection ports are really well made. I already has a Micro USB cable from Ambrane and it's still in good shape. I connected my phone to the car using the cable and it got connected well and no issues. I also connected it to the charging port and yes it has Fast Charging support.,It quality is good at this price and the main thing is that i didn't ever thought that this cable will be so long it's good one and charging power is too good and also supports fast charging,Value for money, with extra length👍,Good, working fine,Product quality is good,Good,very good,Bought for my daughter's old phone.Brand new cable it was not charging, I already repacked and requested for replacement.I checked again, and there was some green colour paste/fungus inside the micro USB connector. I cleaned with an alcoholic and starts working again.Checked the ampere of charging speed got around 1400ma-1500ma - not bad, came with braided 1.5m long cable, pretty impressive for the price.Can't blame the manufacturer.But quality issues by the distributor, they might have stored in very humid place.",https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31zOsqQOAOL._SY445_SX342_QL70_FMwebp_.jpg,https://www.amazon.in/Ambrane-Unbreakable-Charging-Braided-Cable/dp/B098NS6PVG/ref=sr_1_2?qid=1672909124&s=electronics&sr=1-2
2,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹199,"₹1,899",90%,3.9,"7,928","【 Fast Charger& Data Sync】-With built-in safety proctections and four-core copper wires promote maximum signal quality and strength and enhance charging & data transfer speed with up to 480 mb/s transferring speed.|【 Compatibility】-Compatible with iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS devices.|【 Sturdy & Durable】-The jacket and enforced connector made of TPE and premium copper, are resistant to repeatedly bending and coiling.|【 Ultra High Quality】: According to the experimental results, the fishbone design can accept at least 20,000 bending and insertion tests for extra protection and durability. Upgraded 3D aluminum connector and exclusive laser welding technology, which to ensure the metal part won't break and also have a tighter connection which fits well even with a protective case on and will never loose connection.|【 Good After Sales Service】-Our friendly and reliable customer service will respond to you within 24 hours ! you can purchase with confidence,and every sale includes a 365-day worry-free Service to prove the importance we set on quality.","AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQLWQOWZ4N3OA,AHTPQRIMGUD4BYR5YIHBH3CCGEFQ,AEUVWXYP5LT7PZLLZENEO2NODPBQ,AHC7MPW55DOO6WNCOQVA2VHOD26A,AFDI6FRPFBTNBG7BAEB7JDJSMKDQ,AFQKCEEEKXCOHTDG4WUN3XPPHJQQ,AHKUUFNMBZIDLSSPA4FEHIO2EC7Q","Kunal,Himanshu,viswanath,sai niharka,saqib malik,Aashiq,Ramu Challa,Sanjay gupta","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R25X4TBMPY91LX,R27OK7G99VK0TR,R207CYDCHJJTCJ,R3PCU8XMU173BT,R1IMONDOWRNU5V","Good speed for earlier versions,Good Product,Working good,Good for the price,Good,Worth for money,Working nice,it's a really nice product","Not quite durable and sturdy,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71rIggrbUCL._SY88.jpg,Working good,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61bKp9YO6wL._SY88.jpg,Product,Very nice product,Working well,It's a really nice product",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31IvNJZnmdL._SY445_SX342_QL70_FMwebp_.jpg,https://www.amazon.in/Sounce-iPhone-Charging-Compatible-Devices/dp/B096MSW6CT/ref=sr_1_3?qid=1672909124&s=electronics&sr=1-3
3,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹329,₹699,53%,4.2,"94,363","The boAt Deuce USB 300 2 in 1 cable is compatible with smartphones, tablets, PC peripherals, Bluetooth speakers, power banks and all other devices with Type-C as well as Micro USB port|It ensures 3A fast charging and data transmissions with rapid sync at 480 mbps|The premium Nylon braided skin makes it sturdy and invincible against external damage|Its Aluminium alloy shell housing makes it last longer with 10000+ Bends Lifespan with extended frame protection for strain relief|The resilient and flexible design offers a tangle free experience seamlessly|Deuce USB 300 cable offers a perfect 1.5 meters in length for smooth & hassle-free user experience|2 years warranty from the date of purchase","AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5SGCUQBP7YSCA,AH725ST5NW2Y4JZPKUNTIJCUK2BA,AHV3TXIFCJPMS4D5JATCEUR266MQ,AGWIGDEMFIIUAOXYY2QATNBSUGHA,AFSTSLQUV4EVEXWKBOLEFHL2H5YQ,AGAKDNBHY2FKX7I4ACRGILU7QL7A,AFNWJUWJRHCC6HN52KMG5AKZY37Q","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh chouhan,Ravi Siddan,Himanshu Goel,Udaykumar","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1CLH2ULIVG5U3,R2DMKIBGFKBD6R,RC89B5IAJUTR5,R3B3DDON5FH8DS,R13WAEJDI5RS36","Good product,Good one,Nice,Really nice product,Very first time change,Good,Fine product but could be better,Very nice it's charging like jet","Good product,long wire,Charges good,Nice,I bought this cable for Rs.339 worthy product for this price, i tested it in various charger adapters 33w and 18w it supports fast charging as well.,Good,Ok,I had got this at good price on sale on Amazon and product is useful with warranty but for warranty you need to go very far not practical for such a cost and mine micro to type c connector stopped working after few days only.,I like this product",https://m.media-amazon.com/images/I/41V5FtEWPkL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Deuce-300-Resistant-Tangle-Free-Transmission/dp/B08HDJ86NZ/ref=sr_1_4?qid=1672909124&s=electronics&sr=1-4
4,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹154,₹399,61%,4.2,"16,905","[CHARGE & SYNC FUNCTION]- This cable comes with charging & Data sync function|[HIGH QUALITY MATERIAL]- TPE + Nylon Material to make sure that the life of the cable is enhanced significantly|[LONG CORD]- The Cable is extra thick 1.2 meter long, optimized for an easy use for your comfort at home or office|[MORE DURABLE]-This cable is unique interms of design and multi-use and is positioned to provide the best comfort and performance while using|[UNIVERSAL COMPATIBILITY]- Compatible with all devices like iPhone XS, X, XR, 8, 7, 6S, 6, 5S, iPad Pro, iPad mini and iPad Air","AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZHM4QB2KPKFUQ,AFK4NJOLFSJGWLOJIUIAROJF6YVA,AFUOTYRFUXVPEBGIXVZZ7DR3CZUA,AFDLRSXKDZ6U3U3KD46SQLFGZQRA,AH5VLM66SIK7J3IRG4NY7XVOQ55A,AE3MQNNHHLUHXURL5S7IAR7JTGNQ,AFSEOFZY67MYC7UAJU264Z5NFTLA","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK,Bhargav,Durai Vignesh,Amazon Customer","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R3KK4GT934ST3I,RCFHMWUSBIJO,RDO7DACXMAJ84,R3A6MEZL3LY66Z,R1ESIEKPGAYA29","As good as original,Decent,Good one for secondary use,Best quality,GOOD,Amazing product at a mind blowing price!,Nice Quality,Good product","Bought this instead of original apple, does the work for 150rs, not as fast as apple charger but its a good option if you want cheap and good product, bought it for iPad pro 10.5 and it's working flawlessly, build quality is ok, its not like i am gonna hang my clothes on it and i want a very strong cable, even a braided cable stop working after a year, i have used both Anker and Apple store strong braided cable they all stop working after a year so please don't buy high end cables just for that instead choose a this one and even if it's stops working withing a year you only loose 150rs compares to 2000rs.UPDATE------------------------------------pin has stopped charging from one side, now i have to slip the pin to charge from other side, but i will update and let know for how long does it work,,It’s good. Not sure about durability as the pin area feels a bit fragile,Does not support apple carplaySo was little disappointed about thatOther than that cable is made up of very good quality,Best to buy,100% NOT FATHFUL,Writing this review post 10 months and 3 orders of the same product.Honestly Portronics Konnect L lightning cable works like magic with the original Apple charging brick.Seeing the price of the cable I initially hesitated buying as it was as low as ₹99/- with the offers and so I wasn’t sure if it would work well with my iPhone 12 or whether it would impact my iPhone’s battery health because all the other lightning cable brands were costing over ₹350/- like Wayona, Amazon Basics, etc.Earlier I was using Wayona Brand lightning cable with eventually frayed and stopped working.Charging Speed:Charges my iPhone fast enough almost similar compared to the original cable level when used with 12W Original Apple power adapter.Quality and Durability:Great quality braided cable and doesn’t tangle easily and can withstand day-to-day usage.L-Shaped pin:This is very innovative by Portronics and it makes sure the cable doesn’t get damaged even if used while charging.CarPlay and Data Sync:Works smoothly with CarPlay and syncs data effortlessly.PS: I have used this cable only with the Original Apple Charging Brick and extremely satisfied with its performance.,Better than I expect the product I like that Quality and I plan to buy same type cable come with usb C to Lighting cable for emergency purpose that much I love this cable. Buy for this cable only emergency uses only since Good one,Good product and value for money",https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31VzNhhqifL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Portronics-Konnect-POR-1080-Charging-Function/dp/B08CF3B7N1/ref=sr_1_5?qid=1672909124&s=electronics&sr=1-5

In [3]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 1465
Columns : 16

In [4]:
df.columns.tolist()

['product_id',
 'product_name',
 'category',
 'discounted_price',
 'actual_price',
 'discount_percentage',
 'rating',
 'rating_count',
 'about_product',
 'user_id',
 'user_name',
 'review_id',
 'review_title',
 'review_content',
 'img_link',
 'product_link']

In [5]:
df.dtypes

product_id             str
product_name           str
category               str
discounted_price       str
actual_price           str
discount_percentage    str
rating                 str
rating_count           str
about_product          str
user_id                str
user_name              str
review_id              str
review_title           str
review_content         str
img_link               str
product_link           str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 4.7 MB

In [7]:
df.isnull().sum().sort_values(ascending=False)

rating_count           2
product_id             0
category               0
product_name           0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [8]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [9]:
df.sample(5, random_state=42)

     product_id  \
976  B09XXZXQC1
175  B09LHXNZLR
275  B09LV13JFB
548  B08M66K48D
869  B07KRCW6LZ

                                                                                                                                                                                           product_name  \
976                         Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz Refresh Rate| 6GB, 128GB| 2.5K+ Display (10.95-inch/27.81cm)|1 Billion Colours| Dolby Vision Atmos| Quad Speakers| Wi-Fi| Gray
175       Skadioo WiFi Adapter for pc | Car Accessories, WiFi Dongle for pc | USB WiFi Adapter for pc | Wi-Fi Receiver 2.4GHz, 802.11b/g/n UNano Size WiFi Dongle Compatible Adapter,WiFi dongle for pc
275                                                                  LOHAYA Voice Assistant Remote Compatible for Airtel Xstream Set-Top Box Remote Control with Netflix Function (Black) (Non - Voice)
548                                        POPIO Tempered Glass Screen Protector Compatible for iPhone 12 / iPhone 12 Pro with Case Friendly Edge to Edge Coverage and Easy Installation kit, Pack of 1
869  TP-Link Nano AC600 USB Wi-Fi Adapter(Archer T2U Nano)- 2.4G/5G Dual Band Wireless Network Adapter for PC Desktop Laptop, Mini Travel Size, Supports Windows 11,10, 8.1, 8, 7, XP/Mac OS 10.9-10.15

                                                                                          category  \
976                                                                  Computers&Accessories|Tablets
175                    Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters
275                                    Electronics|HomeTheater,TV&Video|Accessories|RemoteControls
548  Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors
869                    Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters

    discounted_price actual_price discount_percentage rating rating_count  \
976          ₹26,999      ₹37,999                 29%    4.6        2,886
175             ₹199         ₹499                 60%    3.7          612
275             ₹399         ₹999                 60%    3.3           23
548             ₹299         ₹599                 50%    4.3        4,674
869             ₹999       ₹1,599                 38%    4.3       12,093

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     about_product  \
976                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Qualcomm Snapdragon 860 Octa-core processor | 6GB RAM | 128GB Internal Storage|WQHD+ (2560x1600 high resolution) 10.95" Dolby Vision display | 120Hz refresh rate | Supports DCI-P3 with over 1 billion colours|Quad Speakers with Dolby Atmos | Long lasting 8720 mAh Battery | Android 11|13MP Rear Camera with 4K recording | 8MP Front camera | Ultra Slim design
175  【Powerful compatibility】 Compatible with TV box, Windows XP / Vista / 7 / 8 / 10, Mac OS and Linux. The ultra-fast speed of the wireless adapter with the latest 802.11ac WiFi technology ensures a non-general web experience.|The device will not work with the systems that have no option to install device driver , so would not be compatible with DVR's . NVR's , Set top box , Music players , Car audio systems or any other device on which you can't install drivers|【Ultra High Speed】The USB WiFi adapter is equipped with 802.11n WiFi technology for faster speed and dual band, reducing interference and avoiding unexpected connection breaks or signal loss. Maximum speed up to 600 Mbpsat 2.4GHz, ideal for movies, HD video streaming, online gaming and video chatting.|【Support any WiFi router and AP mode】 with the USB Wi-Fi adapter, you can upgrade your TV box, PC, laptop or Mac and work with the latest AC Wi-Fi router for faster speed and longer range. In Soft AP mode, a wired internet connection can be converted into a Wi-Fi hotspot that provides Wi-Fi signal to your mobile devices. Besides, the built-in antenna design makes the Wi-Fi signal more stable and much stronger.|【Mini WiFi Dongle Design】Super mini size, compact USB WiFi adapter for easy carrying. You can leave it in your TV box, laptop or PC and don't need to remove it.
275                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         100% Best Quality Plastic Body and Soft Silicone Rubber Keypad|Remotes are checked by Testing Machine Before Shipment|Imported Generic Product Not by Airtel|Please Match the Image with Your Existing Remote Before Placing the Order
548                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Hardness: High hardness level provides protection from accidental drop & scratches|Additional features: Bubble proof, Scratch resistant, Anti fingerprint, Anti-glare, Anti-shatter, Touch sensitive|Easy Installation: Contains 1 Tempered Glass Screen Protector, 1 wet wipe, 1 dry wipe, 1 Dust Absorber & 3 Guide Stickers|Compatible Device: iPhone 12 / iPhone 12 Pro | Area of coverage: Edge to Edge Full Screen Coverage|Item Hardness: 9H Hardness
869                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           High Speed WiFi —— Up to 600Mbps speeds with 200Mbps on 2.4GHz and 433 Mbps on 5GHz, upgrades your devices to higher AC WiFi speeds|Dual Band Wireless —— 2.4GHz and 5GHz band for flexible connectivity, upgrades your devices to work with the latest dual-band WiFi router for faster speed and extended range|Nano design —— Small, unobtrusive design allows you to plug it in and forget it is even there|Operating System —— Supports Windows 11/10/8.1/8/7/XP, Mac OS 10.15 and earlier|Advanced Security —— Supports 64/128-bit WEP, WPA/WPA2, and WPA-PSK/WPA2-PSK encryption standards|Worry-free customer support —— For other installation related query, compatibility issue or any other queries call on toll free no

                                                                                                                                                                                                                                     user_id  \
976                                                                                                                      AGIQYUS55MG4UWXTEF4PRMPZWPQA,AH4VWAKSTYSTM4XW5I4VA4VOGL6A,AGXLDDFUAUJIXQ5SZK2CKHJGCO4A,AFDV3XB5P65LS5FRSIEWKAY3K3JQ
175  AG2Q7FISK54KBSPHF7CNNGZ3GLNA,AFFYX3FR3SF4JOIN7FIPEVVTIRMQ,AFUBGC56G63INVGIAA2OOMZDRLTQ,AEQWGO62V6K2GSMRMFGRW35NBTQA,AF7USQ27RIKU5ABXWZG2WFECW7JQ,AGZT5FACORYIGQP6G2H2CS6HEMTQ,AFUQWSUM2FGNLHU45YUKN3QAEFHQ,AHVGMS3MGWLQZG2IR34ENSS4UX4Q
275                                                                                         AERUC72DWRPOM2EHX3YBTBPKYV7A,AHMH6RNLYI2G65HY7POX4SHBVD3Q,AEHIVP567T6DNMLNZKGOVUENP5YA,AGEE4II4FA6IYCAZ47PLZD7XRPSQ,AFE5HMMFE5Z3EJZYWVIOHHTHDTPA
548  AHH26HAPTOI5Z52DFLNYU5TOLWCQ,AFIPAA4KT36MSZTCVAITRIUVJCNQ,AEYXCHSBU6NC4ZKH4OOFYZZTQJFA,AG4CH37VZG5JRJCAEYYGYTFH5UWQ,AGGCXXWA7CJVTHA22YE7PTNWQ7NQ,AFNQO7B5IZKARACZBIO74VFTU6EA,AH3ABVXQTD6ZA64V6NTEJL66RV7A,AFKY3NTT4T35K67VJ2RIO76YDK2Q
869  AEM356PVXFHAXWV56KDO75FS5WPA,AHVTFTBEBRRJCG72ZG7ABDNQSAOA,AHFTFGF2YB5ZEUB3NC3KOBGZBG5Q,AEI36WUCG27UYFAGDF7HX74VEGIA,AGW3NGXVSGUB34Q5V6ACANURQMGQ,AEIMBDWSM42YEDEE6476WUXFZJHQ,AHM5MCT3ZO5Q2MBYZUDB6UI5AXLA,AFTPXYKUNENYJVDOC55L2CJXPXFQ

                                                                                                            user_name  \
976                                                            & I Am IronMan,Amazon Customer,Sayandeep Sarkar,sherin
175  POTNURU RAJINI,swapnil mohit masih,Suryansh Bhargava,I.KANNAN,Prakshobh,karthikeyan,sandeep kumar,Abhiram Ganesh
275                                                           Amazon Customer,Amazon Customer,Akul,Akash Yadav,ambika
548                                   Ram K,Ankush,Viswanathan,Sanchita Mandal,Malhotra A.,Roy,ravi verma,Pravi Gupta
869                          Paul Joe,Simon Rex P. J.,Santhosh,Rajat Singh 2,Placeholder,Jay,VARUN PANDEY,Jai Jyothir

                                                                                                                   review_id  \
976                                                               R2BT60BZIDC986,R17KDJGM0QOT3P,R2U9CP6B4FEVBN,RJ29G3M313IFR
175     R3U57AW0L6O5C6,R3FCLH5G7XVDU4,R39PNKDT86WK5V,RINNKP59LVQ2F,R2NMOPMWX8DV8,R2ZFSEQ2HU3CY1,RHS9HYJMJGCAN,R1SN2CUL4M8ZMG
275                                                R1P2VLNHZAHSCU,R28B2GC0X0RMKW,RQ2S0N0NGDQVY,R19KN24ZE86FRJ,R2R1RIQO9D9HNF
548  R2K2YNHJ952H5J,R1I8HU4RYFCVYW,R2DH2MLDOFTD73,R35L5ENDJ4MHKH,R3GBYEZ0GVZWLC,R1774TGNOXHCP3,R3RHTIGZI3S51Q,R2378C6LJXZXO1
869    RSNHWPVLK9SAQ,R2RKKAN3GRHI0G,R1FVWKC3ORTKKX,RTWMPZGIX9EDV,R3TRCC0769D12A,R2NJK9AW0NVU1C,R3M97OC4YJNBQT,R2IUPWWR3XMJ3D

                                                                                                                                                                                                                 review_title  \
976  the only ANDROID tablet that makes sense in the non-sense tab market of India.,An impressive tablet for Android (at last),All good but miner bugs just don't upgrade it to 13.0.6.. New update details given,good tablet
175                                                                                                                                       Good,Very nice,Best quality,Not bad,Best WiFi module,good,Working fine,Good Product
275                When I placed the order I was in doubt whether it would work or not but it works very well,Very bad 😞😞,Remote very 👎 bad,Doesn’t works at all, material quality isn’t nearby the original one,No bluetooth
548               Big Bubble dont go away,Perfect tempered glass in given price,Nice,Overall good but difficult to install,Good quality and great price,Best Tempered Glass👌🏻,Good quality,Best tempered glass used till date
869                         Dual Bandwidth,It's good,Simple and effective,Easy plug and play,Only 200mbps support,Great Device for Old Laptops,Good device but be careful for a defective one.,Excellent Speeds and Coverage!
