In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
from src.recommender import RecommendationEngine

engine = RecommendationEngine()

engine.train("../data/processed/amazon_cleaned.csv")

engine.recommend("iphone cable")

Dataset loaded successfully!
Shape: (1337, 12)
TF-IDF Matrix Created
(1337, 5000)
Cosine Similarity Matrix Created
(1337, 1337)
Indices Created
Recommendation Engine Ready!

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Final Score,Why Recommended,Image,Amazon Link
0,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",Computers Accessories Accessories Peripherals ...,249.0,999.0,75.0,5.0,5179.0,0.4986,0.5502,Related product | Highly rated | Frequently re...,https://m.media-amazon.com/images/I/31-q0xhaTA...,https://www.amazon.in/REDTECH-Lightning-Certif...
1,Amazonbasics Nylon Braided Usb-C To Lightning ...,Computers Accessories Accessories Peripherals ...,899.0,1900.0,53.0,4.4,13552.0,0.4852,0.5188,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/3183iGEWks...,https://www.amazon.in/AmazonBasics-Apple-Certi...
2,Belkin Apple Certified Lightning To Type C Cab...,Computers Accessories Accessories Peripherals ...,1499.0,1999.0,25.0,4.4,1951.0,0.4730,0.5076,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Belkin-Lightning-iPhone-...
3,"ESR USB C to Lightning Cable, 10 ft (3 m), MFi...",Computers Accessories Accessories Peripherals ...,1519.0,1899.0,20.0,4.4,19763.0,0.4182,0.4734,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/41I2mS67Dy...,https://www.amazon.in/ESR-Lightning-MFi-Certif...
4,AmazonBasics USB C to Lightning Aluminum with ...,Computers Accessories Accessories Peripherals ...,949.0,1999.0,53.0,4.4,13552.0,0.4070,0.4641,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/41JooboBmu...,https://www.amazon.in/AmazonBasics-Lightning-A...
5,AmazonBasics USB C to Lightning Aluminum with ...,Computers Accessories Accessories Peripherals ...,949.0,1999.0,53.0,4.4,13552.0,0.4008,0.4598,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/AmazonBasics-Lightning-A...
6,Wayona Nylon Braided (2 Pack) Lightning Fast U...,Computers Accessories Accessories Peripherals ...,649.0,1999.0,68.0,4.2,24269.0,0.4070,0.4586,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/412fvb7k2F...,https://www.amazon.in/Wayona-Braided-WN3LG2-Sy...
7,Wayona Type C to Lightning MFI Certified 20W F...,Computers Accessories Accessories Peripherals ...,719.0,1499.0,52.0,4.1,1045.0,0.4182,0.4570,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Lightning-Certifi...
8,Wayona Type C to Lightning MFI Certified 20W F...,Computers Accessories Accessories Peripherals ...,719.0,1499.0,52.0,4.1,1045.0,0.4120,0.4527,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-charging-Nylon-Br...
9,SWAPKART Fast Charging Cable and Data Sync USB...,Computers Accessories Accessories Peripherals ...,209.0,499.0,58.0,3.9,536.0,0.4142,0.4461,Related product,https://m.media-amazon.com/images/I/41KmCJuybR...,https://www.amazon.in/SWAPKART-Charging-Compat...

In [3]:
engine.recommend("usb c")

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Image,Amazon Link
0,SWAPKART Fast Charging Cable and Data Sync USB...,Computers Accessories Accessories Peripherals ...,209.0,499.0,58.0,3.9,536.0,0.7060,https://m.media-amazon.com/images/I/41KmCJuybR...,https://www.amazon.in/SWAPKART-Charging-Compat...
1,Syncwire LTG to USB Cable for Fast Charging Co...,Computers Accessories Accessories Peripherals ...,399.0,1999.0,80.0,5.0,5.0,0.4436,https://m.media-amazon.com/images/I/317OoQfs1g...,https://www.amazon.in/Syncwire-Cable-Charging-...
2,"Hi-Mobiler iPhone Charger Lightning Cable,2 Pa...",Computers Accessories Accessories Peripherals ...,254.0,799.0,68.0,4.0,2905.0,0.3564,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Charging-Certified-Light...
3,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers Accessories Accessories Peripherals ...,399.0,1099.0,64.0,4.2,24269.0,0.3487,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
4,Wayona Type C to Lightning MFI Certified 20W F...,Computers Accessories Accessories Peripherals ...,719.0,1499.0,52.0,4.1,1045.0,0.3378,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-charging-Nylon-Br...
5,Wayona Type C to Lightning MFI Certified 20W F...,Computers Accessories Accessories Peripherals ...,719.0,1499.0,52.0,4.1,1045.0,0.3367,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Lightning-Certifi...
6,MYVN LTG to USB for Fast Charging & Data Sync ...,Computers Accessories Accessories Peripherals ...,252.0,999.0,75.0,3.7,2249.0,0.3343,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/MYVN-Fast-Charging-Compa...
7,AmazonBasics USB C to Lightning Aluminum with ...,Computers Accessories Accessories Peripherals ...,949.0,1999.0,53.0,4.4,13552.0,0.3333,https://m.media-amazon.com/images/I/41JooboBmu...,https://www.amazon.in/AmazonBasics-Lightning-A...
8,AmazonBasics USB C to Lightning Aluminum with ...,Computers Accessories Accessories Peripherals ...,949.0,1999.0,53.0,4.4,13552.0,0.3295,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/AmazonBasics-Lightning-A...
9,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",Computers Accessories Accessories Peripherals ...,249.0,999.0,75.0,5.0,5179.0,0.3191,https://m.media-amazon.com/images/I/31-q0xhaTA...,https://www.amazon.in/REDTECH-Lightning-Certif...

In [3]:
engine.recommend("wireless mouse")

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Final Score,Why Recommended,Image,Amazon Link
0,"Dell WM118 Wireless Mouse, 2.4 Ghz with USB Na...",Computers Accessories Accessories Peripherals ...,569.0,1299.0,56.0,4.4,9275.0,0.5216,0.5433,Similar product | Well rated | Frequently revi...,https://m.media-amazon.com/images/I/31959YGwwi...,https://www.amazon.in/DELL-WM118-Wireless-Opti...
1,"Logitech M221 Wireless Mouse, Silent Buttons, ...",Computers Accessories Accessories Peripherals ...,799.0,1295.0,38.0,4.4,34852.0,0.5113,0.5421,Similar product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/31ROHZJMEU...,https://www.amazon.in/Logitech-Silent-Wireless...
2,"Logitech M235 Wireless Mouse, 1000 DPI Optical...",Computers Accessories Accessories Peripherals ...,699.0,995.0,30.0,4.5,54405.0,0.4755,0.5256,Related product | Highly rated | Popular among...,https://m.media-amazon.com/images/I/31CtVvtFt+...,https://www.amazon.in/Logitech-M235-Wireless-M...
3,Amazon Basics Wireless Mouse | 2.4 GHz Connect...,Computers Accessories Accessories Peripherals ...,499.0,1000.0,50.0,5.0,23.0,0.4581,0.5207,Related product | Highly rated,https://m.media-amazon.com/images/I/31+Rg6Z46d...,https://www.amazon.in/Wireless-Connection-Batt...
4,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers Accessories Accessories Peripherals ...,1295.0,1645.0,21.0,4.6,12375.0,0.4641,0.5118,Related product | Highly rated | Popular among...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
5,Logitech MK215 Wireless Keyboard and Mouse Com...,Computers Accessories Accessories Peripherals ...,1295.0,1795.0,28.0,4.1,25771.0,0.4272,0.4691,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-MK215-Wireless-...
6,HP Z3700 Wireless Optical Mouse with USB Recei...,Computers Accessories Accessories Peripherals ...,899.0,1499.0,40.0,4.2,23174.0,0.4193,0.4669,Related product | Well rated | Popular among c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/HP-Z3700-Wireless-Mouse-...
7,"Lenovo 400 Wireless Mouse, 1200DPI Optical Sen...",Computers Accessories Accessories Peripherals ...,629.0,1390.0,55.0,4.4,6301.0,0.3940,0.4533,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lenovo-GY50R91293-Wirele...
8,Logitech MK240 Nano Wireless USB Keyboard and ...,Computers Accessories Accessories Peripherals ...,1495.0,1995.0,25.0,4.3,7241.0,0.3666,0.4303,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/I/41tLaG2nSp...,https://www.amazon.in/Logitech-MK240-NANO-Mous...
9,"Zebronics Zeb-Jaguar Wireless Mouse, 2.4GHz wi...",Computers Accessories Accessories Peripherals ...,399.0,1190.0,66.0,4.1,2809.0,0.3713,0.4246,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/I/31BXpfrkEW...,https://www.amazon.in/Zebronics-Zeb-Jaguar-Wir...

In [5]:
engine.recommend("boat speaker")

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Image,Amazon Link
0,Zebronics Zeb Wonderbar 10 USB Powered 2.0 Com...,Computers Accessories Accessories Peripherals ...,849.0,1499.0,43.0,4.0,7352.0,0.1788,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Zebronics-Wonderbar-Powe...
1,Cubetek 3 in 1 LCD Display V5.0 Bluetooth Tran...,"Electronics HomeTheater,TV Video AVReceivers A...",1990.0,3100.0,36.0,4.0,897.0,0.1648,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bluetooth-Transmitter-Re...
2,Zebronics ZEB-COUNTY 3W Wireless Bluetooth Por...,Electronics HomeAudio Speakers BluetoothSpeakers,549.0,999.0,45.0,3.9,64705.0,0.1614,https://m.media-amazon.com/images/I/41goRo3UXh...,https://www.amazon.in/Zebronics-Zeb-County-Blu...
3,AmazonBasics 10.2 Gbps High-Speed 4K HDMI Cabl...,"Electronics HomeTheater,TV Video Accessories C...",609.0,1500.0,59.0,4.5,1029.0,0.1410,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/AmazonBasics-High-Speed-...
4,EGate i9 Pro-Max 1080p Native Full HD Projecto...,"Electronics HomeTheater,TV Video Projectors",9490.0,15990.0,41.0,3.9,10480.0,0.1393,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Support-Display-Projecto...
5,BlueRigger High Speed HDMI Cable with Ethernet...,"Electronics HomeTheater,TV Video Accessories C...",467.0,599.0,22.0,4.4,44054.0,0.1385,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/BlueRigger-High-Speed-Ca...
6,Amazon Basics 10.2 Gbps High-Speed 4K HDMI Cab...,"Electronics HomeTheater,TV Video Accessories C...",499.0,900.0,45.0,4.4,2165.0,0.1340,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/AmazonBasics-High-Speed-...
7,AmazonBasics - High-Speed Male to Female HDMI ...,"Electronics HomeTheater,TV Video Accessories C...",299.0,700.0,57.0,4.4,8714.0,0.1314,https://m.media-amazon.com/images/I/41BIgj-8fM...,https://www.amazon.in/AmazonBasics-High-Speed-...
8,BlueRigger Digital Optical Audio Toslink Cable...,"Electronics HomeTheater,TV Video Accessories C...",416.0,599.0,31.0,4.2,30023.0,0.1295,https://m.media-amazon.com/images/I/41CF6GtnpK...,https://www.amazon.in/BlueRigger-Digital-Optic...
9,"CableCreation RCA to 3.5mm Male Audio Cable, 3...","Electronics HomeTheater,TV Video Accessories C...",439.0,758.0,42.0,4.2,4296.0,0.1285,https://m.media-amazon.com/images/I/41Bh7qwDUm...,https://www.amazon.in/Cablecreation-Audio-Cabl...

In [6]:
engine.recommend("gaming keyboard")

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Image,Amazon Link
0,Zebronics Wired Keyboard and Mouse Combo with ...,Computers Accessories Accessories Peripherals ...,448.0,699.0,36.0,3.9,17348.0,0.3382,https://m.media-amazon.com/images/I/3164hjUSFd...,https://www.amazon.in/Zebronics-Zeb-JUDWAA-750...
1,Zebronics ZEB-KM2100 Multimedia USB Keyboard C...,Computers Accessories Accessories Peripherals ...,329.0,399.0,18.0,3.6,33735.0,0.3072,https://m.media-amazon.com/images/I/41XQP3N-Sd...,https://www.amazon.in/Zebronics-Km2100-Multime...
2,Dell KB216 Wired Multimedia USB Keyboard with ...,Computers Accessories Accessories Peripherals ...,549.0,1799.0,69.0,4.3,28829.0,0.2721,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Dell-KB216-Wired-Multime...
3,Dell USB Wireless Keyboard and Mouse Set- KM33...,Computers Accessories Accessories Peripherals ...,1399.0,2498.0,44.0,4.2,33717.0,0.2670,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Dell-Wireless-Keyboard-M...
4,Zebronics Zeb-Companion 107 USB Wireless Keybo...,Computers Accessories Accessories Peripherals ...,699.0,999.0,30.0,3.5,15295.0,0.2597,https://m.media-amazon.com/images/I/41UUBwBt05...,https://www.amazon.in/Zebronics-Zeb-Companion-...
5,Logitech MK270r USB Wireless Keyboard and Mous...,Computers Accessories Accessories Peripherals ...,1345.0,2295.0,41.0,4.2,17413.0,0.2526,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Wireless-mk270r...
6,Logitech MK215 Wireless Keyboard and Mouse Com...,Computers Accessories Accessories Peripherals ...,1295.0,1795.0,28.0,4.1,25771.0,0.2379,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-MK215-Wireless-...
7,Portronics Key2 Combo Multimedia USB Wireless ...,Computers Accessories Accessories Peripherals ...,1149.0,1499.0,23.0,4.1,10443.0,0.2204,https://m.media-amazon.com/images/I/41bX3o-ZHq...,https://www.amazon.in/Portronics-Multimedia-Wi...
8,Quantum QHM-7406 Full-Sized Keyboard with (₹) ...,Computers Accessories Accessories Peripherals ...,299.0,599.0,50.0,3.8,3066.0,0.2108,https://m.media-amazon.com/images/I/41y181oD7Z...,https://www.amazon.in/Quantum-QHM-7406-Spill-R...
9,Logitech MK240 Nano Wireless USB Keyboard and ...,Computers Accessories Accessories Peripherals ...,1495.0,1995.0,25.0,4.3,7241.0,0.2027,https://m.media-amazon.com/images/I/41tLaG2nSp...,https://www.amazon.in/Logitech-MK240-NANO-Mous...

In [3]:
engine.recommend(
    "wireless mouse",
    min_rating=4.3
)

,Product,Category,Price,Actual Price,Discount (%),Rating,Rating Count,Similarity,Final Score,Why Recommended,Image,Amazon Link
0,"Dell WM118 Wireless Mouse, 2.4 Ghz with USB Na...",Computers Accessories Accessories Peripherals ...,569.0,1299.0,56.0,4.4,9275.0,0.5216,0.5433,Similar product | Well rated | Frequently revi...,https://m.media-amazon.com/images/I/31959YGwwi...,https://www.amazon.in/DELL-WM118-Wireless-Opti...
1,"Logitech M221 Wireless Mouse, Silent Buttons, ...",Computers Accessories Accessories Peripherals ...,799.0,1295.0,38.0,4.4,34852.0,0.5113,0.5421,Similar product | Well rated | Popular among c...,https://m.media-amazon.com/images/I/31ROHZJMEU...,https://www.amazon.in/Logitech-Silent-Wireless...
2,"Logitech M235 Wireless Mouse, 1000 DPI Optical...",Computers Accessories Accessories Peripherals ...,699.0,995.0,30.0,4.5,54405.0,0.4755,0.5256,Related product | Highly rated | Popular among...,https://m.media-amazon.com/images/I/31CtVvtFt+...,https://www.amazon.in/Logitech-M235-Wireless-M...
3,Amazon Basics Wireless Mouse | 2.4 GHz Connect...,Computers Accessories Accessories Peripherals ...,499.0,1000.0,50.0,5.0,23.0,0.4581,0.5207,Related product | Highly rated,https://m.media-amazon.com/images/I/31+Rg6Z46d...,https://www.amazon.in/Wireless-Connection-Batt...
4,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers Accessories Accessories Peripherals ...,1295.0,1645.0,21.0,4.6,12375.0,0.4641,0.5118,Related product | Highly rated | Popular among...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
5,"Lenovo 400 Wireless Mouse, 1200DPI Optical Sen...",Computers Accessories Accessories Peripherals ...,629.0,1390.0,55.0,4.4,6301.0,0.3940,0.4533,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lenovo-GY50R91293-Wirele...
6,Logitech MK240 Nano Wireless USB Keyboard and ...,Computers Accessories Accessories Peripherals ...,1495.0,1995.0,25.0,4.3,7241.0,0.3666,0.4303,Related product | Well rated | Frequently revi...,https://m.media-amazon.com/images/I/41tLaG2nSp...,https://www.amazon.in/Logitech-MK240-NANO-Mous...